### ISSUE TITLE
MS_MAP_PATTERN regex cannot be compiled

### ISSUE THREAD

**Issue by remyguillaume** [camptocamp/docker-mapserver#151]
Hi there,

I am using the docker image camptocamp/mapserver:7.6, and I'm getting an error with MS_MAP_PATTERN.
I landed here, and saw that the were a commit for this error a couple of minutes ago, so I just tried with the very last docker image (https://hub.docker.com/layers/camptocamp/mapserver/7.6/images/sha256-1f079b8eef8049a599b4a152990c0bae802d972e3bf3d6723c1a7c7651d87e7a?context=explore), but I'm still having the regex validation error:

`msCGILoadMap(): Web application error. CGI variable "map" fails to validate. msEvalRegex(): Regular expression error. Failed to compile expression (^/etc/mapserver/([^.][_A-Za-z0-9-.]+/{1})*([_A-Za-z0-9-.]+.map)$).`

Any Idea ?
Thanks!

**Comment by sbrunner** [comment]
Fixed this morning: https://github.com/camptocamp/docker-mapserver/pull/144 and backported on all branches :-)

**Comment by remyguillaume** [comment]
But I've just tried the fix : https://hub.docker.com/layers/camptocamp/mapserver/7.6/images/sha256-1f079b8eef8049a599b4a152990c0bae802d972e3bf3d6723c1a7c7651d87e7a?context=explore

(In the error message, the missing parenthesis is present)
And I'm still getting the validation error.
Did I miss something ?
